// src/MyApp.jsx
import Table from "./Table";
import Form from "./Form";
import React, { useState, useEffect } from "react"; // process to requesting data 


function MyApp() {
  const [characters, setCharacters] = useState([
   
  ]);

  function removeOneCharacter(index) {
    const updated = characters.filter((character, i) => i !== index);
    setCharacters(updated);
  }

  function updateList(person) {
  postUser(person)
    .then(() => setCharacters([...characters, person]))
    .catch((error) => {
      console.log(error);
    });
}


// ----------- conncet with backend-----------
function fetchUsers() {
  const promise = fetch("http://localhost:8000/users"); // promise generated by fetch
  return promise;
}

useEffect(() => {
  fetchUsers()
    .then((res) => res.json())
    .then((json) => setCharacters(json["users_list"])) // use json to parse
    .catch((error) => {
      console.log(error);
    });
}, []);
// -------------- request calls to add a new user to backend 
function postUser(person) {
  // fetch send promise to backend
  const promise = fetch("http://localhost:8000/users", { // return a promise 
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(person),
  })
  // then reply to the message
  .then((res) => {
    if (res.status === 201){
      return res.json();
    }
    else {
      return undefined; // front end can read, react, parse but not send error
    }

  });

  return promise;
}
// 

  return (
    <div className="container">
      <Table characterData={characters} 
      removeCharacter={removeOneCharacter} />
      <Form handleSubmit={updateList}/>
    </div>
  );
}

export default MyApp;
