// src/MyApp.jsx
import Table from "./Table";
import Form from "./Form";
import React, { useState, useEffect } from "react"; // process to requesting data 


function MyApp() {
  const [characters, setCharacters] = useState([
   
  ]);

  function removeOneCharacter(index) {
    const updated = characters.filter((character, i) => i !== index);
    setCharacters(updated);
  }

  function updateList(person) {
    setCharacters([...characters, person]);
  }


// ----------- conncet with backend-----------
function fetchUsers() {
  const promise = fetch("http://localhost:8000/users"); // promise generated by fetch
  return promise;
}

useEffect(() => {
  fetchUsers()
    .then((res) => res.json())
    .then((json) => setCharacters(json["users_list"])) // use json to parse
    .catch((error) => {
      console.log(error);
    });
}, []);

  return (
    <div className="container">
      <Table characterData={characters} 
      removeCharacter={removeOneCharacter} />
      <Form handleSubmit={updateList}/>
    </div>
  );
}

export default MyApp;
